// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	groupsList: () => typedError<Group[], CommandError>(__TAURI_INVOKE("groups_list")),
	groupCreate: (name: string) => typedError<Group, CommandError>(__TAURI_INVOKE("group_create", { name })),
	groupRename: (id: GroupId, name: string) => typedError<null, CommandError>(__TAURI_INVOKE("group_rename", { id, name })),
	groupReorder: (ids: GroupId[]) => typedError<null, CommandError>(__TAURI_INVOKE("group_reorder", { ids })),
	groupDelete: (id: GroupId) => typedError<null, CommandError>(__TAURI_INVOKE("group_delete", { id })),
	groupSetNeverSendToAi: (id: GroupId, neverSendToAi: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("group_set_never_send_to_ai", { id, neverSendToAi })),
	itemsList: (groupId: GroupId) => typedError<ItemPreview[], CommandError>(__TAURI_INVOKE("items_list", { groupId })),
	itemsSearch: (query: string) => typedError<ItemPreview[], CommandError>(__TAURI_INVOKE("items_search", { query })),
	itemGet: (id: ItemId) => typedError<ItemView, CommandError>(__TAURI_INVOKE("item_get", { id })),
	itemDelete: (id: ItemId) => typedError<null, CommandError>(__TAURI_INVOKE("item_delete", { id })),
	itemUndoDelete: (id: ItemId) => typedError<null, CommandError>(__TAURI_INVOKE("item_undo_delete", { id })),
	captureSave: (target: CaptureTarget) => typedError<Group, CommandError>(__TAURI_INVOKE("capture_save", { target })),
	captureDiscard: () => typedError<null, CommandError>(__TAURI_INVOKE("capture_discard")),
	pasteItem: (id: ItemId, flavour: PasteFlavour) => typedError<null, CommandError>(__TAURI_INVOKE("paste_item", { id, flavour })),
	pasteAll: (groupId: GroupId, order: PasteOrder, separator: PasteSeparator) => typedError<null, CommandError>(__TAURI_INVOKE("paste_all", { groupId, order, separator })),
	pasteAiResult: (resultId: string) => typedError<null, CommandError>(__TAURI_INVOKE("paste_ai_result", { resultId })),
	panelClose: () => typedError<null, CommandError>(__TAURI_INVOKE("panel_close")),
	aiReformat: (itemId: ItemId, preset: ReformatPreset) => typedError<AiResult, CommandError>(__TAURI_INVOKE("ai_reformat", { itemId, preset })),
	aiSummarize: (groupId: GroupId, order: PasteOrder, separator: PasteSeparator, preset: SummaryPreset) => typedError<AiResult, CommandError>(__TAURI_INVOKE("ai_summarize", { groupId, order, separator, preset })),
	aiKeySet: (provider: AiProvider, key: string) => typedError<null, CommandError>(__TAURI_INVOKE("ai_key_set", { provider, key })),
	aiKeyDelete: (provider: AiProvider) => typedError<null, CommandError>(__TAURI_INVOKE("ai_key_delete", { provider })),
	aiKeyStatus: () => typedError<AiKeyStatus, CommandError>(__TAURI_INVOKE("ai_key_status")),
	aiTestConnection: (provider: AiProvider) => typedError<null, CommandError>(__TAURI_INVOKE("ai_test_connection", { provider })),
	settingsGet: () => typedError<Settings, CommandError>(__TAURI_INVOKE("settings_get")),
	settingsUpdate: (patch: SettingsPatch) => typedError<Settings, CommandError>(__TAURI_INVOKE("settings_update", { patch })),
	shortcutSet: (action: ShortcutAction, chord: string) => typedError<null, CommandError>(__TAURI_INVOKE("shortcut_set", { action, chord })),
	platformInfo: () => typedError<PlatformInfo, CommandError>(__TAURI_INVOKE("platform_info")),
	permissionStatus: () => typedError<PermissionStatus, CommandError>(__TAURI_INVOKE("permission_status")),
	permissionOpenSettings: () => typedError<null, CommandError>(__TAURI_INVOKE("permission_open_settings")),
	windowOpen: (kind: WindowKind) => typedError<null, CommandError>(__TAURI_INVOKE("window_open", { kind })),
	diagnosticsExport: () => typedError<string, CommandError>(__TAURI_INVOKE("diagnostics_export")),
	usageClear: () => typedError<null, CommandError>(__TAURI_INVOKE("usage_clear")),
};

/** Events */
export const events = {
	dataGroupsChanged: makeEvent<DataGroupsChanged>("data:groups-changed"),
	dataItemsChanged: makeEvent<DataItemsChanged>("data:items-changed"),
	panelHidden: makeEvent<PanelHidden>("panel:hidden"),
	panelShow: makeEvent<PanelShow>("panel:show"),
	permissionChanged: makeEvent<PermissionChanged>("permission:changed"),
	settingsChanged: makeEvent<SettingsChanged>("settings:changed"),
};

/* Types */
export type AiError = { kind: "no_key" } | { kind: "invalid_key" } | { kind: "rate_limited"; retry_after_secs: number | null } | { kind: "quota_exhausted" } | { kind: "overloaded" } | { kind: "blocked" } | { kind: "network" } | { kind: "other"; message: string };

export type AiKeyStatus = {
	anthropic: boolean,
	openai: boolean,
	gemini: boolean,
};

export type AiProvider = "anthropic" | "openai" | "gemini";

export type AiResult = {
	result_id: string,
	text: string,
};

export type CapturePreview = {
	plain_text: string,
	has_rich_text: boolean,
	image_url: string | null,
};

export type CaptureTarget = { kind: "existing"; group_id: GroupId } | { kind: "new"; name: string };

export type CommandError = { kind: "not_found" } | { kind: "validation"; detail: {
	field: string,
} } | { kind: "conflict" } | { kind: "permission_missing" } | { kind: "target_elevated" } | { kind: "nothing_selected" } | { kind: "unsupported" } | { kind: "too_large" } | { kind: "keychain_unavailable" } | { kind: "ai_locked" } | { kind: "ai"; detail: AiError } | { kind: "internal" };

export type DataGroupsChanged = null;

export type DataItemsChanged = {
	group_id: GroupId,
};

export type DisplaySession = "x11" | "wayland";

export type Group = {
	id: GroupId,
	name: string,
	position: number,
	never_send_to_ai: boolean,
	created_at: number,
};

export type GroupId = number;

export type ItemId = number;

export type ItemPreview = {
	id: ItemId,
	plain_text: string,
	has_rich_text: boolean,
	image_url: string | null,
};

export type ItemView = { kind: "text"; text: string; has_rich_text: boolean } | { kind: "link"; url: string } | { kind: "image"; image_url: string; width: number; height: number };

export type PanelHidden = null;

export type PanelShow = { mode: "copy"; capture: CapturePreview } | { mode: "paste" };

export type PasteFlavour = "default" | "plain";

export type PasteOrder = "oldest_first" | "newest_first";

export type PasteSeparator = "new_line" | "blank_line" | "space" | "comma" | "bulleted_list" | "numbered_list";

export type PermissionChanged = {
	status: PermissionStatus,
};

export type PermissionStatus = "granted" | "missing" | "not_required";

export type PlatformInfo = {
	os: PlatformOs,
	session: DisplaySession | null,
};

export type PlatformOs = "macos" | "windows" | "linux";

export type ReformatPreset = "fix_grammar" | "shorten" | "make_formal";

export type Settings = {
	theme?: Theme,
	shortcuts?: Shortcuts,
	vim_mode?: boolean,
	launch_at_login?: boolean,
	usage_stats?: boolean,
	retention_limit?: number,
	auto_delete_days?: number | null,
	ai_provider?: AiProvider | null,
	ai_model?: string | null,
};

export type SettingsChanged = null;

export type SettingsPatch = {
	theme?: Theme | null,
	vim_mode?: boolean | null,
	launch_at_login?: boolean | null,
	usage_stats?: boolean | null,
	retention_limit?: number | null,
	auto_delete_days?: number | null,
	ai_provider?: AiProvider | null,
	ai_model?: string | null,
};

export type ShortcutAction = "copy_to_group" | "paste_from_group";

export type Shortcuts = {
	copy_to_group: string,
	paste_from_group: string,
};

export type SummaryPreset = "summarise";

export type Theme = "light" | "dark" | "system";

export type UsageMetric = "captures" | "capture_failures" | "pastes" | "paste_degraded" | "panel_opens" | "panel_cancels" | "searches" | "searches_without_result" | "undos" | "ai_requests_succeeded" | "ai_requests_failed" | "panel_open_ms" | "capture_ms" | "paste_ms" | "panel_open_to_paste_ms";

export type WindowKind = "main" | "settings" | "onboarding";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

